{{- if .Values.ingress.enabled -}}
{{- $fullName := include "aiqa.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-app
  labels:
    app: &app {{ template "aiqa.name" . }}-app
    release: &release {{ .Release.Name }}
    chart: {{ template "aiqa.chart" . }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .service }}
              servicePort: 80
        {{- end }}
{{- end }}
# vim:ts=2:sw=2:et:syn=yaml:
