{{- range $micro, $config := .Values.micro }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "aiqa.fullname" $ }}-{{ $micro }}
  labels:
    app: &app {{ template "aiqa.name" $ }}-{{ $micro }}
    release: &release {{ $.Release.Name }}
    chart: {{ template "aiqa.chart" $ }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: *app
      release: *release
  template:
    metadata:
      labels:
        app: *app
        release: *release
    spec:
      containers:
        - name: {{ $.Chart.Name }}-{{ $micro }}
          image: {{ $config.image.repository }}:{{ $config.image.tag }}
          imagePullPolicy: {{ $config.image.pullPolicy }}
          ports:
            - containerPort: 80
          {{ if $config.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $config.readiness.path | default "/healthz" }}
              port: {{ $config.readiness.port | default 80 }}
            initialDelaySeconds: 5
            periodSeconds: 5
          {{ end }}
          envFrom:
            - configMapRef:
                name: {{ template "aiqa.fullname" $ }}-{{ $micro }}
      restartPolicy: Always
{{- end }}
# vim:ts=2:sw=2:et:syn=yaml:
